### ISSUE TITLE
[PE-D][Tester B] Help message not being informative enough for delete command.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-2/tp#116]
![image.png](https://raw.githubusercontent.com/bennyLCK/ped/main/files/b46ee67c-b9ee-4a7c-b347-aecdab944566.png)

As shown by the image above, I think it would be even better if you could also remind the user that he can also simply delete by `index` too and so there is no need to look at individual `uids`.

Perhaps something like: "Please delete by UID or INDEX, for example: delete uid/101 or delete 2."

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: bennyLCK/ped#7

**Comment by PyromancerBoom** [comment]
This seems to be resolved already
