### ISSUE TITLE
[PE-D][Tester B] Unmark command does not remove the 'X' immediately for the employee entry represented in the UI.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-2/tp#122]
![image.png](https://raw.githubusercontent.com/bennyLCK/ped/main/files/b5da0f4e-dbb9-43c2-a617-43c89e0c50da.png)

Let's say we use the template data, and look at the first entry for "Alex Yeoh" again.

I attempt to mark the first task so I run the `mark uid/101 1` command, and it is marked with a `X` as expected.

![image.png](https://raw.githubusercontent.com/bennyLCK/ped/main/files/bfcb2cd8-cea9-4645-8012-f80a684708af.png)

After which, I try to unmark the same task by running `unmark uid/101 1`,

![image.png](https://raw.githubusercontent.com/bennyLCK/ped/main/files/b48972b2-59f0-4446-b66c-8978ceede5f3.png)

But this time round, after I performed the `unmark` command, the success message is given, yet the `X` is still visibly there.

Finally, I closed the application and reopened it, then I see that now, the `X` disappears like magic, I'm stunned like vegetable.

![image.png](https://raw.githubusercontent.com/bennyLCK/ped/main/files/043ebc9a-691a-4e63-81cd-dada0ed0623a.png)

I suspect this visual bug may be because the `unmark` is incorrectly implemented to only do so for the underlying list without modifying the current displayed list to the user, please refer to how `edit` and other commands which modify both the displayed and underlying lists concurrently.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: bennyLCK/ped#13

**Comment by hjungwoo01** [comment]
Due to the feature freeze for v1.4, a fix for this issue cannot be implemented at this time. It is scheduled to be addressed in a future iteration. This is an auto-ui refresh issue.
