### ISSUE TITLE
[PE-D][Tester D] Issues in UG quick start section

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-2/tp#89]
Typo in line 4, should be contactswift.jar not addressbook.jar.
Pictures in the UG also do not load properly as seen below.

![image.png](https://raw.githubusercontent.com/youdonnnn/ped/main/files/b8e1be08-938b-4943-ab6a-ffd9720b5fa3.png)

This could be confusing for readers that require visual guide.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: youdonnnn/ped#1

**Comment by hjungwoo01** [comment]
This is the same as Issues 87 and 88. Both have been resolved.
