### ISSUE TITLE
[PE-D][Tester D] UI does not show tasks added to employees

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-2/tp#94]
I used the command `addTask uid/106 do stuff`, however the task did not show up on the ui until I clicked on the employee. I have attached screenshots below.

After I entered the command:
![image.png](https://raw.githubusercontent.com/youdonnnn/ped/main/files/a6a06f6b-8cac-4008-85bb-0ccd4de9d4c2.png)

After I click on it:
![image.png](https://raw.githubusercontent.com/youdonnnn/ped/main/files/6248a1de-24cb-4d81-aeca-b115ca0440ed.png)

This might be confusing for users who are not as tech-saavy, since they expect the tasks to be updated as soon as the command is entered.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: youdonnnn/ped#2

**Comment by hjungwoo01** [comment]
Due to the feature freeze for v1.4, a fix for this issue cannot be implemented at this time. It is scheduled to be addressed in a future iteration. This is not an addTask command issue, it is an auto-ui refresh issue.
