### ISSUE TITLE
[PE-D][Tester D] UI does not show task as marked/unmarked after input of command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-2/tp#96]
The input command was `mark uid/101 1`. However, after input as been entered, the ui did not reflect this change as seen below.

![image.png](https://raw.githubusercontent.com/youdonnnn/ped/main/files/3b8b50f3-1912-4e0d-bb2a-fa0a624e720f.png)

The ui only updates when I click on the employee.

![image.png](https://raw.githubusercontent.com/youdonnnn/ped/main/files/942a4e81-0552-464c-b9ea-9d95b7420a61.png)

There is the same issue with `unmark uid/101 1` input.

This might cause misunderstandings between the user and their employees as the UI might show a task as undone even though the employee has reported that they have finished their task and the user has keyed it in ContactSwift but he forgot he already keyed it in.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: youdonnnn/ped#3

**Comment by hjungwoo01** [comment]
Due to the feature freeze for v1.4, a fix for this issue cannot be implemented at this time. It is scheduled to be addressed in a future iteration.
